[tools]
cosign            = "latest"
git-cliff         = "latest"
go                = "1.25.6"
golangci-lint     = "2.8.0"
goreleaser        = "latest"
just              = "1.46.0"
markdownlint-cli2 = "0.20.0"
pre-commit        = "4.5.1"
python            = "3.13"
syft              = "latest"
uv                = "latest"
