[tools]
git-cliff         = "latest"
golangci-lint     = "2.8.0"
goreleaser        = "latest"
just              = "1.46.0"
markdownlint-cli2 = "0.20.0"
pre-commit        = "4.5.1"
uv                = "latest"

[settings]
idiomatic_version_file_enable_tools = [ "go", "python" ]
